# Similar to ci-bun.yml, but has an extra step to trigger a Render deployment when tests pass.
# You must create a secret named RENDER_DEPLOY_HOOK_URL in your repository.

on:
  pull_request:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Run unit tests
        run: bun run test

      - name: Trigger deploy
        # Only proceed if the branch is master
        if: github.ref == 'refs/heads/master'
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: curl "$deploy_url"
