# Publish a package to npm when a tag starting with "v" is pushed to remote.
# You must create a secret named NPM_AUTH_TOKEN in your repository.
# Currently, only npm supports publishing packages with provenance
# https://docs.npmjs.com/generating-provenance-statements

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: bun install

      - name: Build package
        run: bun run build

      - name: Publish package
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        run: npm publish --provenance --access public
